#! /bin/bash

headphones=88:C9:E8:06:FD:4F
bluetoothctl power on
bluetoothctl agent on
bluetoothctl discoverable on
bluetoothctl pairable on
grep "$headphones" -m 1 <(stdbuf -oL bluetoothctl --timeout 5 scan on)
bluetoothctl connect "$headphones" || bluetoothctl remove "$headphones"
