#! /bin/sh

headphones=88:C9:E8:06:FD:4F
bluetoothctl power on
bluetoothctl agent on

if ! bluetoothctl connect "$headphones"; then
  bluetoothctl remove "$headphones"
  bluetoothctl pair "$headphones"
fi
